language: go

os:
  - linux
  - osx

before_install:
  - curl https://ready-steady.github.io/travis/fortran.sh | bash

install:
  - go get -d -t ./...
  - make install

script:
  - go test -v

addons:
  apt:
    packages:
      - gfortran

notifications:
  email: false
