language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get -d -t ./...
  - git submodule update --init
  - make install
  - make test

notifications:
  email:
    on_success: never
