language: go
sudo: false

os:
  - linux
  - osx

before_install:
  - curl https://ready-steady.github.io/travis/install_gfortran.sh | bash
  - echo $CGO_LDFLAGS;

install:
  - go get -d -t ./...
  - make install

script:
  - go test -v

notifications:
  email: false

addons:
  apt:
    packages:
      - gfortran
