language: go
sudo: false

os:
  - linux
  - osx

before_install:
  - curl -O https://ready-steady.github.io/travis/install-gfortran.sh
  - source install-gfortran.sh

install:
  - go get -d -t ./...
  - make install

script:
  - go test -v

notifications:
  email: false

addons:
  apt:
    packages:
      - gfortran
