language: go
sudo: false

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export CGO_LDFLAGS="-L$(dirname $(find $(brew --prefix) -name libgfortran.dylib | grep -v i386))";
      echo $CGO_LDFLAGS;
    fi

install:
  - echo $CGO_LDFLAGS
  - go get -d -t ./...
  - make install

script:
  - echo $CGO_LDFLAGS
  - go test -v

notifications:
  email: false

addons:
  apt:
    packages:
      - gfortran
